export const a = 3.4;
export const v0 = 18;
export const v0Max = 21;
export const delta = 0.75;
export const W = 100;
export const y0 = W*.9;
export const car = { length: 2, width: 1 };
export const px = { height: 650, width: 500 };
// export const LaneWidth = 