export const total = 140;
export const vf = (60 * 1000) / 3600; /* 60 kph to m/s */
export const GR = (1 + Math.sqrt(5)) / 2;
export const carLength = 3;
export const carWidth = 1.5;
export const roadWidth = 5;
export const sj = 4;
export const kj = 1 / sj;
export const k0 = kj / 3.5;
export const q0 = vf * k0;
export const w = q0 / (kj - k0);
export const delta = 0.25;
export const cycle = 25;
export const T = cycle * 0.75;
export const X = total * 0.7;
export const xCut = total * 0.15;
export const tCut = cycle * 0.15;
